### ISSUE TITLE
Suggested cleanups

### ISSUE THREAD

**Issue by kostis** [kritonios01/grace-compiler#1]
Since I do not have permissions to create branches, rather than creating a PR here with some of fixes below, is a list of suggested changes:

1. Make sure that `setup.sh` is executable (has `+x` permission),  Currently, it has not when one clones the repository.
2. The compiler should not be verbose by default (e.g. print "XX lines read",  "Syntax OK", "Semantics OK", etc. messages).  If you would like to maintain this functionality for debugging purposes add some appropriate flag (`-v`, `--verbose`) that enables it.
3. The default file that the compiler generates should be `a.out` not the name of the benchmark (e.g. change the line in `main.ml` from `clang ... '"-o "^ filename));` to `clang ... " -o a.out"));`).  If you want to preserve this functionality, add a `-o` / `--output` option to specify the name of the resulting executable.
4. The compiler should cleanup after itself: it should not leave around `.ll`, `.o`, etc. files.
5. **Most important:** the created executable should return 0 on successful execution; the current functionality does not do that and gives the impression that the execution has resulted in some error.  In other words, the generated `a.out` file for `hello.grc` should print two "Hello world!" lines when executed as follows: `./a.out && ./a.out`.  Currently, it prints only one.

**Comment by kritonios01** [comment]
Hello and thanks for your issue! I have now adjusted everything according to what you described.
